# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

Vagrant.configure("2") do |config|

    num_cpus = ENV['VAGRANTMANAGER_CPU']
    mem_size = ENV['VAGRANTMANAGER_MEM']

    config.package.name = "vagrantmanager.box"
    config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", mem_size ? mem_size : 4096]
        vb.customize ["modifyvm", :id, "--cpus",  num_cpus ? num_cpus : 2]
    end

    config.vm.network :private_network, ip: "192.168.70.4"
end
