# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"

    num_cpus              = ENV['VAGRANTMANAGER_CPU']
    mem_size              = ENV['VAGRANTMANAGER_MEM']
    aws_user_name         = ENV['AWS_USER_NAME']
    aws_access_key_id     = ENV['AWS_ACCESS_KEY_ID']
    aws_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    docker_user_name      = ENV['DOCKER_USER_NAME']
    docker_password       = ENV['DOCKER_PASSWORD']
    docker_email          = ENV['DOCKER_EMAIL']

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", mem_size ? mem_size : 6096]
        vb.customize ["modifyvm", :id, "--cpus",  num_cpus ? num_cpus : 2]
    end

    config.vm.network :private_network, ip: "192.168.70.4"

    # mount provisioning
    provisioning_dir = File.expand_path("../../")
    config.vm.synced_folder provisioning_dir, "/opt/web-page-test"

    config.vm.provision "shell" do |s|
        s.path = "startup.sh"
        s.args   = [
            "#{aws_user_name}",
            "#{aws_access_key_id}",
            "#{aws_secret_access_key}",
            "#{docker_user_name}",
            "#{docker_password}",
            "#{docker_email}",
        ]
    end

end
