# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"

    num_cpus = ENV['VAGRANTMANAGER_CPU']
    mem_size = ENV['VAGRANTMANAGER_MEM']

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", mem_size ? mem_size : 4096]
        vb.customize ["modifyvm", :id, "--cpus",  num_cpus ? num_cpus : 2]
    end

    config.vm.network :private_network, ip: "192.168.70.4"

    # mount provisioning
    provisioning_dir = File.expand_path("../../")
    config.vm.synced_folder provisioning_dir, "/opt/web-page-test"

    config.vm.provision :shell, :path => "startup.sh"

end
